
import type { CatalogItem } from '../types';

export const INITIAL_ITEM_CATALOG: CatalogItem[] = [
    // F&B - Fruits & Vegetables
    { name: 'برتقال', category: 'F&B', unit: 'كيلو', estimatedCost: 6.05 },
    { name: 'شمام', category: 'F&B', unit: 'كيلو', estimatedCost: 5.71 },
    { name: 'ريحان أخضر', category: 'F&B', unit: 'كيلو', estimatedCost: 100.00 },
    { name: 'زعتر أخضر', category: 'F&B', unit: 'كيلو', estimatedCost: 100.00 },
    { name: 'روزماري أخضر', category: 'F&B', unit: 'كيلو', estimatedCost: 100.00 },
    { name: 'بطيخ', category: 'F&B', unit: 'كيلو', estimatedCost: 3.45 },
    { name: 'عنب احمر', category: 'F&B', unit: 'كيلو', estimatedCost: 22.03 },
    { name: 'عنب ابيض', category: 'F&B', unit: 'كيلو', estimatedCost: 20.00 },
    { name: 'رمان', category: 'F&B', unit: 'كيلو', estimatedCost: 15.00 },
    { name: 'اناناس', category: 'F&B', unit: 'كيلو', estimatedCost: 12.27 },
    { name: 'فاكهة التنين', category: 'F&B', unit: 'كيلو', estimatedCost: 18.44 },
    { name: 'موز', category: 'F&B', unit: 'كيلو', estimatedCost: 6.77 },
    { name: 'تفاح احمر', category: 'F&B', unit: 'كيلو', estimatedCost: 8.07 },
    { name: 'تفاح اخضر', category: 'F&B', unit: 'كيلو', estimatedCost: 9.24 },
    { name: 'فراولة', category: 'F&B', unit: 'كيلو', estimatedCost: 43.33 },
    { name: 'كيوي', category: 'F&B', unit: 'كيلو', estimatedCost: 17.02 },
    { name: 'مانجو', category: 'F&B', unit: 'كيلو', estimatedCost: 13.43 },
    { name: 'يوسفي', category: 'F&B', unit: 'كيلو', estimatedCost: 9.86 },
    { name: 'برقوق احمر', category: 'F&B', unit: 'كيلو', estimatedCost: 16.76 },
    { name: 'توت احمر 125 جرام', category: 'F&B', unit: 'حبة', estimatedCost: 16.00 },
    { name: 'توت ازرق 125 جرام', category: 'F&B', unit: 'حبة', estimatedCost: 13.50 },
    { name: 'توت اسود 125 جرام', category: 'F&B', unit: 'حبة', estimatedCost: 16.00 },
    { name: 'رد كارنت 125 جرام', category: 'F&B', unit: 'حبة', estimatedCost: 35.00 },
    { name: 'جريب فروت', category: 'F&B', unit: 'كيلو', estimatedCost: 7.88 },
    { name: 'افوكادو', category: 'F&B', unit: 'كيلو', estimatedCost: 20.00 },
    { name: 'فجل احمر', category: 'F&B', unit: 'كيلو', estimatedCost: 2.73 },
    { name: 'بروكلي', category: 'F&B', unit: 'كيلو', estimatedCost: 8.75 },
    { name: 'طماطم', category: 'F&B', unit: 'كيلو', estimatedCost: 3.86 },
    { name: 'طماطم شيري', category: 'F&B', unit: 'كيلو', estimatedCost: 29.00 },
    { name: 'خيار', category: 'F&B', unit: 'كيلو', estimatedCost: 4.20 },
    { name: 'فلفل اصفر الوان', category: 'F&B', unit: 'كيلو', estimatedCost: 14.00 },
    { name: 'فلفل احمر الوان', category: 'F&B', unit: 'كيلو', estimatedCost: 14.00 },
    { name: 'فلفل اخضر الوان', category: 'F&B', unit: 'كيلو', estimatedCost: 7.76 },
    { name: 'فلفل اخضر شطة', category: 'F&B', unit: 'كيلو', estimatedCost: 8.57 },
    { name: 'ثوم', category: 'F&B', unit: 'كيلو', estimatedCost: 11.11 },
    { name: 'بقدونس', category: 'F&B', unit: 'كيلو', estimatedCost: 2.73 },
    { name: 'كزبرة خضراء', category: 'F&B', unit: 'كيلو', estimatedCost: 7.50 },
    { name: 'جرجير', category: 'F&B', unit: 'كيلو', estimatedCost: 3.43 },
    { name: 'ليمون أصفر', category: 'F&B', unit: 'كيلو', estimatedCost: 11.29 },
    { name: 'نعناع', category: 'F&B', unit: 'كيلو', estimatedCost: 8.92 },
    { name: 'بطاطس', category: 'F&B', unit: 'كيلو', estimatedCost: 2.07 },
    { name: 'بصل احمر', category: 'F&B', unit: 'كيلو', estimatedCost: 4.23 },
    { name: 'بصل ابيض', category: 'F&B', unit: 'كيلو', estimatedCost: 4.44 },
    { name: 'جزر', category: 'F&B', unit: 'كيلو', estimatedCost: 5.31 },
    { name: 'شمندر', category: 'F&B', unit: 'كيلو', estimatedCost: 3.75 },
    { name: 'زنجبيل', category: 'F&B', unit: 'كيلو', estimatedCost: 11.11 },
    { name: 'باذنجان رومي', category: 'F&B', unit: 'كيلو', estimatedCost: 3.68 },
    { name: 'خس بلدي', category: 'F&B', unit: 'كيلو', estimatedCost: 5.24 },
    { name: 'خس أمريكي', category: 'F&B', unit: 'كيلو', estimatedCost: 10.59 },
    { name: 'خس الوان', category: 'F&B', unit: 'كيلو', estimatedCost: 26.67 },
    { name: 'كوسة', category: 'F&B', unit: 'كيلو', estimatedCost: 5.00 },
    { name: 'مشروم', category: 'F&B', unit: 'كيلو', estimatedCost: 30.00 },
    { name: 'زهرة', category: 'F&B', unit: 'كيلو', estimatedCost: 4.75 },
    
    // F&B - Meats & Dairy
    { name: 'لحم بيف فيليه برازيلي', category: 'F&B', unit: 'كيلو', estimatedCost: 43.70 },
    { name: 'لحم توب سايد غنم استرالي', category: 'F&B', unit: 'كيلو', estimatedCost: 34.50 },
    { name: 'لحم توب سايد بقر استرالي', category: 'F&B', unit: 'كيلو', estimatedCost: 24.00 },
    { name: 'لحم كتف بالعظم نيوزلندي', category: 'F&B', unit: 'كيلو', estimatedCost: 31.42 },
    { name: 'ليه (دهنة) خروف', category: 'F&B', unit: 'كيلو', estimatedCost: 50.00 },
    { name: 'كبدة دجاج 400 جرام', category: 'F&B', unit: 'حبة', estimatedCost: 2.83 },
    { name: 'كبدة غنم', category: 'F&B', unit: 'كيلو', estimatedCost: 14.42 },
    { name: 'سمك فيليه', category: 'F&B', unit: 'كيلو', estimatedCost: 8.00 },
    { name: 'سمك سلمون فيليه', category: 'F&B', unit: 'كيلو', estimatedCost: 70.00 },
    { name: 'سمك سلمون مدخن', category: 'F&B', unit: 'كيلو', estimatedCost: 92.00 },
    { name: 'جمبري مقشر 21/25', category: 'F&B', unit: 'كيلو', estimatedCost: 39.33 },
    { name: 'جمبري جامبو بالقشر 10/20', category: 'F&B', unit: 'كيلو', estimatedCost: 59.75 },
    { name: 'كلماري', category: 'F&B', unit: 'كيلو', estimatedCost: 21.00 },
    { name: 'جبن موزريلا بلوك 3.2 كجم', category: 'F&B', unit: 'كيلو', estimatedCost: 18.57 },
    { name: 'جبنة حلوم 250 جرام', category: 'F&B', unit: 'حبة', estimatedCost: 5.45 },
    { name: 'جبنة بارميزان', category: 'F&B', unit: 'كيلو', estimatedCost: 47.96 },

    // F&B - Bakery & Pantry
    { name: 'خبز توست بريوش 800 جرام', category: 'F&B', unit: 'حبة', estimatedCost: 6.75 },
    { name: 'مكرونة بنا 450 جرام', category: 'F&B', unit: 'حبة', estimatedCost: 3.54 },
    { name: 'زيت ذرة 17 لتر', category: 'F&B', unit: 'جالون', estimatedCost: 119.00 },
    { name: 'سكر ناعم 10 كجم', category: 'F&B', unit: 'كيلو', estimatedCost: 2.75 },
    { name: 'ملح 50 كيلو', category: 'F&B', unit: 'كيلو', estimatedCost: 0.34 },
    { name: 'دقيق', category: 'F&B', unit: 'كيلو', estimatedCost: 3.91 },
    { name: 'أرز مصري', category: 'F&B', unit: 'كيلو', estimatedCost: 6.00 },
    { name: 'بيض كبير 24 كيلو', category: 'F&B', unit: 'طبق', estimatedCost: 14.07 },

    // Engineering - AC & Plumbing
    { name: 'تعبئة أسطوانة غاز لحام', category: 'Engineering', unit: 'Each', estimatedCost: 40 },
    { name: 'أسطوانة فريون 22', category: 'Engineering', unit: 'Each', estimatedCost: 320 },
    { name: 'غطاء مقعد حمام إفرنجي', category: 'Plumbing & Heating', unit: 'Each', estimatedCost: 80 },
    { name: 'هراب أوتوماتيكي', category: 'Plumbing & Heating', unit: 'Each', estimatedCost: 4.43 },
    { name: 'طاسة دش 2020', category: 'Plumbing & Heating', unit: 'Each', estimatedCost: 25 },
    { name: 'سخان فوري', category: 'Plumbing & Heating', unit: 'Each', estimatedCost: 300 },
    { name: 'سيليكون', category: 'Plumbing & Heating', unit: 'Each', estimatedCost: 12 },
    { name: 'شمعة فلتر مياه مرحلة أولى', category: 'Plumbing & Heating', unit: 'Each', estimatedCost: 6.956 },
    
    // Engineering - Electrical
    { name: 'لمبة ليد 4واط أصفر', category: 'Electrical', unit: 'Each', estimatedCost: 4.5 },
    { name: 'لمبة سبوت 7 واط أصفر', category: 'Electrical', unit: 'Each', estimatedCost: 2.61 },
    { name: 'CPVC 1/2 ماسورة', category: 'Electrical', unit: 'Each', estimatedCost: 16.8 },
    { name: 'حجر ريموت AA', category: 'Electrical', unit: 'Each', estimatedCost: 1.619 },
    { name: 'كابستور مكيف 555 korea', category: 'Electrical', unit: 'Each', estimatedCost: 25 },
    { name: 'تيب كهرباء أسود', category: 'Electrical', unit: 'Each', estimatedCost: 3.03 },

    // Engineering - Painting & Decoration
    { name: 'بخاخ دهان', category: 'Painting & Decoration', unit: 'Each', estimatedCost: 5 },
    { name: 'فرشاة دهان 2 إنش', category: 'Painting & Decoration', unit: 'Each', estimatedCost: 2 },
    { name: 'برميل دهان أبيض بلاستيك', category: 'Painting & Decoration', unit: 'Each', estimatedCost: 157.87 },
    { name: 'سكين دهان', category: 'Painting & Decoration', unit: 'Each', estimatedCost: 5 },
    { name: 'رولة صغيرة', category: 'Painting & Decoration', unit: 'Each', estimatedCost: 1.5 },
    { name: 'تيب دهان', category: 'Painting & Decoration', unit: 'Each', estimatedCost: 2.9 },

    // Linens, Maintenance, Furniture (from old mock data)
    { name: 'High-Quality Coffee Beans', category: 'F&B', unit: 'kg', estimatedCost: 40 },
    { name: 'Luxury Bath Towels', category: 'Linens', unit: 'piece', estimatedCost: 25 },
    { name: 'Egyptian Cotton Bed Sheets', category: 'Linens', unit: 'set', estimatedCost: 120 },
    { name: 'Plush Bathrobes', category: 'Linens', unit: 'piece', estimatedCost: 45 },
    { name: 'LED Light Bulbs', category: 'Maintenance', unit: 'piece', estimatedCost: 5 },
    { name: 'Air Filter Replacement', category: 'Maintenance', unit: 'filter', estimatedCost: 15 },
    { name: 'New Lobby Furniture Set', category: 'Furniture', unit: 'set', estimatedCost: 15000 },
    { name: 'Guest Room Desk Chair', category: 'Furniture', unit: 'piece', estimatedCost: 250 },
    { name: 'Cleaning Supplies', category: 'Housekeeping', unit: 'bottle', estimatedCost: 100 },
];